import Head from 'next/head';

import styles from '../styles/Home.module.css';
import Banner from '../components/banner';
import Image from 'next/image';
import Card from '../components/card';

export async function getStaticProps(context) {
    const apikey = 'fsq3L44vmFOn8vPltebp/NLUQ9+H4sJWzApzJzqL7JI4VXk=';

    const searchParams = new URLSearchParams({
        query: 'coffee',
        ll: '41.8781,-87.6298',
        open_now: 'true',
        sort: 'DISTANCE',
    });
    const results = await fetch(
        `https://api.foursquare.com/v3/places/search?${searchParams}`,
        {
            method: 'GET',
            headers: {
                Accept: 'application/json',
                Authorization: apikey,
            },
        },
    );
    const data = await results.json();
    console.log(data);

    return {
        props: {
            coffeeStores: data?.results,
        },
    };
}

//const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
    const bannerBtnClick = () => {};

    return (
        <div className='styles.container'>
            <Head>
                <title>Coffee-app</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
                <title>Coffee Store</title>
            </Head>
            <main className={styles.main}>
                <Banner
                    buttonText='View stores nearby'
                    onBannerBtnClick={bannerBtnClick}
                />
                <div className={styles.heroImage}>
                    <Image
                        src='/static/hero-image.png'
                        width={700}
                        height={400}
                        alt='hero'
                    />
                </div>
                {props.coffeeStores.length > 0 && (
                    <>
                        <h2 className={styles.heading2}>Chicago Stores</h2>
                        <div className={styles.cardLayout}>
                            {props.coffeeStores.map((coffeeStore) => {
                                return (
                                    <Card
                                        name={coffeeStore.name}
                                        href={`/coffee-store/${coffeeStore.id}`}
                                        key={coffeeStore.fsq_id}
                                        imgUrl={
                                            coffeeStore.imgUrl ||
                                            '/static/coffee-store.jpg'
                                        }
                                        className={styles.card}
                                    />
                                );
                            })}
                        </div>
                    </>
                )}
            </main>
        </div>
    );
}
